@baseUrl = http://127.0.0.1:8000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4MzY1MDYyLCJpYXQiOjE3NjgzNjE0NjIsImp0aSI6ImJjYjU3ZDJkMDJmZTQ5YjU4MGIzZjljMjU1NTBlMzZkIiwidXNlcl9pZCI6MjQsInVzZXJuYW1lIjoidXNlcm5hbWU2IiwiZW1haWwiOiJ1c2VybmFtZTZAdXNlci5jb20iLCJncm91cCI6WyJVc3VhcmlvIEJhc2ljbyJdLCJyb2xlIjoiVXN1YXJpbyBCYXNpY28ifQ.F9UA2n_D0ZXcHg06LeLm-rDMA17eK7T9h1SYg4NTmdo
### Login (obtén access token)
POST {{baseUrl}}/api/login/
Content-Type: application/json

{
  "username": "username6",
  "password": "username6"
}

### Obtener profile / estado onboarding (GET)
GET {{baseUrl}}/api/onboarding/
Authorization: Bearer {{accessToken}}

### Completar onboarding (POST)
POST {{baseUrl}}/api/onboarding/
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "date_of_birth": "1990-01-01",
  "height_cm": 180,
  "weight_kg": 75.5,
  "gender": "M"
}

### ------------------------------------------------------------------------
### HISTORIAL (DAILY RECORDS)
### ------------------------------------------------------------------------

### Crear un registro diario (POST)
POST {{baseUrl}}/api/history/
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "date": "2023-10-28",
  "steps": 8500,
  "sleep_hours": 7.5,
  "mood": 4,
  "hydration_ml": 2000
}

### Obtener historial completo (GET)
GET {{baseUrl}}/api/history/
Authorization: Bearer {{accessToken}}