# Generated by Django 5.0.6 on 2026-01-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_dailyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
