# Generated by Django 5.0.6 on 2026-01-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_activity_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bed_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sleep_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='wake_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='wakes_up_at_night',
            field=models.BooleanField(default=False),
        ),
    ]
