# Generated by Django 5.0.6 on 2026-01-22 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_bed_time_profile_sleep_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='calories_kcal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='distance_km',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='sleep_quality',
            field=models.CharField(blank=True, choices=[('Mala', 'Mala'), ('Regular', 'Regular'), ('Buena', 'Buena'), ('Excelente', 'Excelente')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='PhysicalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('Caminata', 'Caminata'), ('Correr', 'Correr'), ('Gimnasio', 'Gimnasio'), ('Natación', 'Natación'), ('Yoga', 'Yoga'), ('Ciclismo', 'Ciclismo'), ('Otro', 'Otro')], max_length=50)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('daily_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='users.dailyrecord')),
            ],
        ),
    ]
